Repository Root-App/root-ruby-style, pull requests merged in 2018-12, with the labels that each got.

#4 Adds tests, better file structure, and CI
  .buildkite/pipeline.yml
  .dockerignore
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  docker-compose.buildkite.yml
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/job_has_queue.rb
  lib/rubocop/cop/root_cops/private_methods/called_private_method.rb
  lib/rubocop/cop/root_cops/private_methods/called_protected.rb
  lib/rubocop/cop/root_cops/private_methods/underscore_prefix.rb
  lib/rubocop/cop/root_cops/raise_i18n.rb
  lib/rubocop/cop/root_cops/shared_context_name.rb
  lib/rubocop/cop/root_cops/spec_file_name.rb
  lib/rubocop/cop/root_cops/use_before_action.rb
  lib/rubocop/cop/root_cops/use_detect.rb
  lib/rubocop/cop/root_cops/use_envvars.rb
  lib/rubocop/cop/root_cops/use_lonely_operator.rb
  lib/rubocop/root_cops/job_has_queue.rb
  lib/rubocop/root_cops/private_methods/called_private_method.rb
  lib/rubocop/root_cops/private_methods/called_protected.rb
  lib/rubocop/root_cops/private_methods/underscore_prefix.rb
  lib/rubocop/root_cops/raise_i18n.rb
  lib/rubocop/root_cops/shared_context_name.rb
  lib/rubocop/root_cops/spec_file_name.rb
  lib/rubocop/root_cops/use_before_action.rb
  lib/rubocop/root_cops/use_detect.rb
  lib/rubocop/root_cops/use_envvars.rb
  lib/rubocop/root_cops/use_lonely_operator.rb
  root-ruby-style.gemspec
  spec/rubocop/cop/root_cops/use_lonely_operator_spec.rb
  spec/spec_helper.rb
Labels: orange-team, ready-for-review

#5 Adds rule to prevent backfill in data migration
  .rubocop.yml
  Gemfile.lock
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/no_backfills_in_data_migration.rb
  root-ruby-style.gemspec
  spec/config/rubocop_config_spec.rb
  spec/rubocop/cop/root_cops/no_backfills_in_data_migrations_spec.rb
  spec/spec_helper.rb
Labels: orange-team

#6 Adds a rule to prevent usage of aggregate_failures
  .rubocop.yml
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/unnecessary_aggregate_failures.rb
  spec/rubocop/cop/root_cops/unnecessary_aggregate_failures_spec.rb
Labels: reviewed, team-black
