Repository Root-App/root-ruby-style, pull requests merged in 2019-04, with the labels that each got.

#11 Revert "Add custom rubocop cop to enforce factory names"
  .rubocop.yml
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/factory_file_name.rb
  spec/rubocop/cop/root_cops/factory_file_name_spec.rb
Labels: FYI, team-application-infrastructure

#12 Add EqBeEql Rubocop extension to enforce eq() for spec test result checks
  .gitignore
  .rubocop.yml
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/eq_be_eql.rb
  spec/rubocop/cop/root_cops/eq_be_eql_spec.rb
  spec/rubocop/cop/root_cops/support/shared_examples.rb
  spec/spec_helper.rb
Labels: reviewed, team-application-infrastructure, team-state-expansion

#13 Bump version to 0.0.2
  Gemfile.lock
  root-ruby-style.gemspec
Labels: reviewed, team-application-infrastructure, team-state-expansion

#10 Create factory-file-name cop and factory-name cop
  .rubocop.yml
  Gemfile.lock
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/factories/factory_file_name.rb
  lib/rubocop/cop/root_cops/factories/factory_name.rb
  lib/rubocop/helpers/factories.rb
  root-ruby-style.gemspec
  spec/rubocop/cop/root_cops/factories/factory_file_name_spec.rb
  spec/rubocop/cop/root_cops/factories/factory_name_spec.rb
  spec/rubocop/helpers/factories_spec.rb
Labels: reviewed, team-application-infrastructure
