Repository Root-App/root-ruby-style, pull requests merged in 2020-03, with the labels that each got.

#29 Warn against too long retry when queuing to SQS
  lib/rubocop/cop/root_cops/retry_on_warning.rb
  spec/rubocop/cop/root_cops/retry_on_warning_spec.rb
Labels: ready-for-review, team-drive-science

#30 Add .rspec
  .rspec
  spec/config/rubocop_config_spec.rb
  spec/rubocop/cop/root_cops/avoid_ruby_prof_spec.rb
  spec/rubocop/cop/root_cops/envvar_assignment_spec.rb
  spec/rubocop/cop/root_cops/eq_be_eql_spec.rb
  spec/rubocop/cop/root_cops/factories/factory_file_name_spec.rb
  spec/rubocop/cop/root_cops/factories/factory_name_spec.rb
  spec/rubocop/cop/root_cops/must_inherit_spec.rb
  spec/rubocop/cop/root_cops/no_backfills_in_data_migrations_spec.rb
  spec/rubocop/cop/root_cops/no_index_on_add_column_spec.rb
  spec/rubocop/cop/root_cops/no_tracers_spec.rb
  spec/rubocop/cop/root_cops/private_methods/called_private_method_spec.rb
  spec/rubocop/cop/root_cops/private_methods/called_protected_spec.rb
  spec/rubocop/cop/root_cops/private_methods/underscore_prefix_spec.rb
  spec/rubocop/cop/root_cops/retry_on_warning_spec.rb
  spec/rubocop/cop/root_cops/unnecessary_aggregate_failures_spec.rb
  spec/rubocop/cop/root_cops/use_detect_spec.rb
  spec/rubocop/cop/root_cops/use_lonely_operator_spec.rb
  spec/rubocop/helpers/factories_spec.rb
  spec/spec_helper.rb
Labels: reviewed, team-reliability

#31 Add UpAndDownOrChange Cop
  .rubocop.yml
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/up_and_down_or_change.rb
  spec/rubocop/cop/root_cops/up_and_down_or_change_spec.rb
Labels: reviewed, team-reliability

#32 Fix Issue Where Constant Is Already Defined
  spec/rubocop/cop/root_cops/no_tracers_spec.rb
Labels: reviewed, team-reliability

#33 Updates rubocop version
  .rubocop.yml
  Gemfile.lock
  root-ruby-style.gemspec
  spec/rubocop/cop/root_cops/avoid_ruby_prof_spec.rb
  spec/rubocop/cop/root_cops/envvar_assignment_spec.rb
  spec/rubocop/cop/root_cops/factories/factory_file_name_spec.rb
  spec/rubocop/cop/root_cops/factories/factory_name_spec.rb
  spec/rubocop/cop/root_cops/must_inherit_spec.rb
  spec/rubocop/cop/root_cops/no_backfills_in_data_migrations_spec.rb
  spec/rubocop/cop/root_cops/no_index_on_add_column_spec.rb
  spec/rubocop/cop/root_cops/private_methods/called_private_method_spec.rb
  spec/rubocop/cop/root_cops/private_methods/called_protected_spec.rb
  spec/rubocop/cop/root_cops/private_methods/underscore_prefix_spec.rb
  spec/rubocop/cop/root_cops/retry_on_warning_spec.rb
  spec/rubocop/cop/root_cops/support/shared_examples.rb
  spec/rubocop/cop/root_cops/unnecessary_aggregate_failures_spec.rb
  spec/rubocop/cop/root_cops/up_and_down_or_change_spec.rb
  spec/rubocop/cop/root_cops/use_detect_spec.rb
  spec/rubocop/cop/root_cops/use_lonely_operator_spec.rb
Labels: reviewed, team-productivity-server

#34 Ignores system name in factory names.
  lib/rubocop/cop/root_cops/factories/factory_name.rb
  spec/rubocop/cop/root_cops/factories/factory_name_spec.rb
Labels: reviewed, team-productivity-server
