Repository Root-App/root-ruby-style, pull requests merged in 2021-08, with the labels that each got.

#47 Update ruby version to 2.7.4
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
Labels: ready-for-review, team-productivity-server

#48 Update Rubocop to 1.18.4
  .rubocop.yml
  Gemfile.lock
  lib/rubocop/cop/root_cops/factories/factory_file_name.rb
  lib/rubocop/cop/root_cops/factories/factory_name.rb
  root-ruby-style.gemspec
  spec/rubocop/cop/root_cops/up_and_down_or_change_spec.rb
  spec/spec_helper.rb
Labels: reviewed, team-productivity-server

#46 MustInclude Cop for asserting module inclusion
  .rubocop.yml
  lib/rubocop/cop/root_cops.rb
  lib/rubocop/cop/root_cops/must_include.rb
  spec/rubocop/cop/root_cops/must_include_spec.rb
Labels: ready-for-review

#50 Allow multiple options for parent class
  lib/rubocop/cop/root_cops/must_inherit.rb
  spec/rubocop/cop/root_cops/must_inherit_spec.rb
Labels: ready-for-review

#51 Detect namespaced constants properly
  lib/rubocop/cop/root_cops/must_include.rb
  lib/rubocop/cop/root_cops/must_inherit.rb
  spec/rubocop/cop/root_cops/must_include_spec.rb
  spec/rubocop/cop/root_cops/must_inherit_spec.rb
Labels: ready-for-review

#52 Remove cop configurations that won't work with include paths
  .rubocop.yml
Labels: ready-for-review, team-productivity-server
